version: '3.9'

services:
  crypto_bot:
    image: crypto_bot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A app.celery.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
