version: '3.9'

services:
  crypto_bot:
    image: crypto_bot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
