[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "crypto-bot"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]          # tells